### ISSUE TITLE
Py3.13 (and latest Py3.12, Py3.11): AttributeError: module 'test.support' has no attribute 'run_unittest' 

### ISSUE THREAD

**Issue by QuLogic** [DanielStutzbach/heapdict#17]
Function test.support.test_unittest() has been removed: https://github.com/python/cpython/commit/fc9a5ef1a8894b2c61dbc762be6a8bf90906b621 

```
+ /usr/bin/python3 test_heap.py
Traceback (most recent call last):
  File "/builddir/build/BUILD/HeapDict-1.0.1/test_heap.py", line 121, in <module>
    test_main(verbose=True)
  File "/builddir/build/BUILD/HeapDict-1.0.1/test_heap.py", line 107, in test_main
    test_support.run_unittest(*test_classes)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'test.support' has no attribute 'run_unittest'
```

and also based on [the docs for `test.support`](https://docs.python.org/3/library/test.html#module-test.support), this should probably not be used.

**Comment by jelly** [comment]
You can simply run the tests using `python -m unittest test_heap.py`

**Comment by QuLogic** [comment]
Thanks, that does work, I guess, since it avoids the `__name__ == "__main__"` clause.
